### ISSUE TITLE
attack_tool.py requires interface to have an IP address 

### ISSUE THREAD

**Issue by MiniAvarec** [raw-packet/raw-packet#35]
While trying to launch "attack_tool.py" script on remote system with several wlan adapters it fails with an error:
```
[!] Please set a wireless network interface ...
[*] Your wireless interface list:
[-] Network interface: wlan1 does not have IP address!
```

**Comment by MiniAvarec** [comment]
Error can be seen here
![ezgif-1-2d31432cde66](https://user-images.githubusercontent.com/3001865/78142408-ba4b7580-744e-11ea-83a3-51360be9ce06.gif)

**Comment by Vladimir-Ivanov-Git** [comment]
https://github.com/raw-packet/raw-packet/commit/f81fe790623f81677b645f61061fb9d4740de80c
