### ISSUE TITLE
attack_tool.py Freezes whole system after interface selection

### ISSUE THREAD

**Issue by MiniAvarec** [raw-packet/raw-packet#37]
After script start, while I am trying to select interface for monitoring, it freezes, loading 1 cpu core up to 100%. 
If script will be restarted it freezes whole system on the "choose interface" step.
OS is raspbian 10 on Raspberry Pi 4.

![Запись_2020_04_01_20_17_49_187](https://user-images.githubusercontent.com/3001865/78148222-70ff2400-7456-11ea-99f5-c1c4457edc30.gif)

**Comment by Vladimir-Ivanov-Git** [comment]
Please run attack_tool.py with argument '-d' (debug mode)
https://github.com/raw-packet/raw-packet/commit/d0d3c1e5bfd50c2714e9e0893e8ea701452ebd78

**Comment by MiniAvarec** [comment]
It produces some output, but behavior is same - freeze
![image](https://user-images.githubusercontent.com/3001865/78163330-140d6900-746a-11ea-86bd-e8c953e797b0.png)

**Comment by Vladimir-Ivanov-Git** [comment]
https://github.com/raw-packet/raw-packet/commit/674c2c2078bb77650b29f8e39ae5fb440cc07ef2

**Comment by Vladimir-Ivanov-Git** [comment]
Please check again

**Comment by MiniAvarec** [comment]
Works good.
Actual problem was in specific feature, which included termination of "wpa_supplicant" process while scan is in progress. 
Usage of dedicated **ethernet** or monitor+keyboard connection solved the problem.
