### ISSUE TITLE
Resolving DNS records

### ISSUE THREAD

**Issue by barrracud4** [raw-packet/raw-packet#7]
Add support to resolve any kind of DNS records (NS, CAA, MX, etc..) in dns_server.py script. It can be released by a possibility to use some kind of configuration file as input to script.

**Comment by Vladimir-Ivanov-Git** [comment]
DNS server config example: https://github.com/raw-packet/raw-packet/blob/master/Scripts/DNS/dns_server_config.json
Start DNS server with config: `python3 raw-packet/Scripts/DNS/dns_server.py -i eth0 -c raw-packet/Scripts/DNS/dns_server_config.json`
